### ISSUE TITLE
Improve regex's for immature words

### ISSUE THREAD

**Issue by LeoGalleguillos** [monthly-basis/content-moderation#3]

**Comment by Alireza-Sampour** [comment]
Hi @LeoGalleguillos, I want to work on this, could you label this issue with hacktoberfest?

**Comment by leo-galleguillos** [comment]
> Hi @LeoGalleguillos, I want to work on this, could you label this issue with hacktoberfest?

Hi, I re-created this issue under my developer GitHub account because I did not want this showing up on my personal account.

You can visit the new issue here:

https://github.com/monthly-basis/content-moderation/issues/6
